import test from 'node:test';import assert from 'node:assert/strict';
import {hashPassword,checkPassword,canRead,cost,meetingPlatform,validateEvidence,nextState} from '../packages/domain/index.mjs';
test('passwords are salted and checked without storing plaintext',()=>{const hash=hashPassword('a-strong-test-password');assert.ok(checkPassword('a-strong-test-password',hash));assert.equal(checkPassword('wrong',hash),false);assert.notEqual(hash,hashPassword('a-strong-test-password'));});
test('tenant boundary precedes administrator privilege',()=>{const admin={id:'a',org_id:'one',roles:['ORG_ADMIN'],unit_ids:[]};assert.equal(canRead(admin,{org_id:'two',owner_id:'a'}),false);assert.equal(canRead(admin,{org_id:'one'}),true);});
test('team membership does not imply another team access',()=>{const member={id:'a',org_id:'one',roles:['MEMBER'],unit_ids:['site']};assert.equal(canRead(member,{org_id:'one',unit_id:'commercial'}),false);assert.equal(canRead(member,{org_id:'one',unit_id:'site'}),true);});
test('cost calculation retains decimal precision and exchange rate',()=>{assert.deepEqual(cost('48','0.0175','7.8'),{usd:'0.84000000',hkd:'6.55200000'});assert.deepEqual(cost('0.1','0.2','7.8'),{usd:'0.02000000',hkd:'0.15600000'});});
test('meeting links reject deceptive suffixes and insecure schemes',()=>{assert.equal(meetingPlatform('https://teams.microsoft.com/l/meetup-join/test'),'Teams');assert.equal(meetingPlatform('https://company.zoom.us/j/123'),'Zoom');for(const url of ['https://zoom.us.evil.test/j/1','https://evilzoom.us/j/1','http://zoom.us/j/1','https://user:password@zoom.us/j/1'])assert.throws(()=>meetingPlatform(url));});
test('approval requires a source quote and explicit reviewer verification',()=>{const segments=[{id:'s1',text:'Morgan will issue the report by 2026-09-23.'}];const good={type:'action',text:'Issue report',evidence:'s1',quote:segments[0].text,owner:'Morgan',dueDate:'2026-09-23',verified:true};assert.deepEqual(validateEvidence({items:[good]},segments),[]);assert.ok(validateEvidence({items:[{...good,verified:false}]},segments).length);assert.ok(validateEvidence({items:[{...good,owner:'Alex'}]},segments).length);assert.ok(validateEvidence({items:[{...good,quote:'Invented claim'}]},segments).length);assert.ok(validateEvidence({items:[{...good,evidence:'another-transcript'}]},segments).length);});
test('approved minutes cannot be edited by lifecycle transition',()=>{assert.equal(nextState('IN_REVIEW','approve'),'APPROVED');assert.equal(nextState('APPROVED','reopen'),'READY_FOR_REVIEW');assert.throws(()=>nextState('READY_FOR_REVIEW','approve'));assert.throws(()=>nextState('APPROVED','submit'));});
