import test from 'node:test';import assert from 'node:assert/strict';
import {RecordingSession,recordingMime,audioExtension} from '../apps/web/src/recording-engine.mjs';
function fixture(){let now=0,released=0,finished;const states=[],chunks=[];const track={stop(){released++;}};const stream={getTracks:()=>[track],getAudioTracks:()=>[track]};
 class FakeRecorder{static isTypeSupported(t){return t==='audio/mp4';}constructor(s,o){this.mimeType=o.mimeType;this.state='inactive';}start(){this.state='recording';}pause(){this.state='paused';}resume(){this.state='recording';}stop(){this.state='inactive';queueMicrotask(()=>{this.ondataavailable({data:new Blob(['final'],{type:this.mimeType})});this.onstop();});}}
 const session=new RecordingSession({getMedia:async()=>stream,Recorder:FakeRecorder,now:()=>now,onChange:s=>states.push(s),onChunk:(...c)=>chunks.push(c),onFinish:(...a)=>{finished=a;}});
 return {session,states,chunks,track,stream,FakeRecorder,setTime:n=>{now=n;},result:()=>({released,finished})};
}
test('Safari MP4 fallback, pause duration and final audio chunk',async()=>{const f=fixture();assert.equal(recordingMime(f.FakeRecorder),'audio/mp4');await f.session.start();f.setTime(2500);f.session.pause();f.setTime(9500);assert.equal(f.session.seconds(),2.5);f.session.resume();f.setTime(11000);f.session.recorder.ondataavailable({data:new Blob(['first'])});f.session.stop();f.session.stop();await new Promise(r=>setImmediate(r));assert.equal(f.result().finished[1],4);assert.equal(await f.result().finished[0].text(),'firstfinal');assert.equal(f.result().finished[0].type,'audio/mp4');assert.equal(audioExtension('audio/mp4;codecs=mp4a.40.2'),'m4a');assert.equal(f.result().released,1);assert.equal(f.chunks.length,2);assert.equal(f.session.state,'ready');});
test('denied microphone permission returns actionable idle state',async()=>{const f=fixture();f.session.getMedia=async()=>{throw Object.assign(new Error(),{name:'NotAllowedError'});};await f.session.start();assert.equal(f.session.state,'idle');assert.match(f.states.at(-1).error,/denied/);assert.equal(f.result().finished,undefined);});
test('permission result after unmount releases microphone without recording',async()=>{const f=fixture();let resolve;f.session.getMedia=()=>new Promise(r=>{resolve=r;});const pending=f.session.start();f.session.dispose();resolve(f.stream);await pending;assert.equal(f.result().released,1);assert.equal(f.session.recorder,undefined);});
test('microphone disconnect preserves final audio and reports interruption',async()=>{const f=fixture();await f.session.start();f.setTime(1200);f.track.onended();await new Promise(r=>setImmediate(r));assert.equal(f.result().finished[1],1.2);assert.match(f.states.at(-1).error,/disconnected/);assert.equal(f.session.state,'ready');});
test('unexpected stop accounts for elapsed time',async()=>{const f=fixture();await f.session.start();f.setTime(1900);f.session.recorder.stop();await new Promise(r=>setImmediate(r));assert.equal(f.result().finished[1],1.9);});
