import React,{useEffect,useRef,useState} from 'react';
import {Waveform,UploadSimple,FloppyDisk,ArrowCounterClockwise,CheckCircle} from '@phosphor-icons/react';
import {api} from './api';
import {Button,Field} from './ui';
import {defaultBrand,fonts,brandVariables,contrast} from './brand';

export function BrandMark({config}){const b={...defaultBrand,...config};return <div className={'brand'+(b.logo?' has-logo':'')}>{b.logo?<img src={b.logo} alt={b.name+' logo'} style={{width:b.logoWidth,maxWidth:'100%'}}/>:<Waveform size={30} color='var(--amber)' weight='bold'/>}{b.showName&&<span>{b.name}</span>}</div>;}

const palettes=[{name:'Original amber',accent:'#ffbf3d',sidebar:'#111d2b',background:'#ffffff',link:'#225cc1'},{name:'Ocean blue',accent:'#2563eb',sidebar:'#10243a',background:'#f6f8fc',link:'#1d4ed8'},{name:'Forest green',accent:'#267356',sidebar:'#142b24',background:'#f7faf8',link:'#226549'},{name:'Plum',accent:'#8054b0',sidebar:'#261b35',background:'#faf8fc',link:'#73449f'}];
export function BrandSettings({user,onSaved,notify}){
 const [form,setForm]=useState(defaultBrand),[saved,setSaved]=useState(null),[revision,setRevision]=useState(null),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState('');
 const fileRef=useRef(),uploadVersion=useRef(0);
 const dirty=JSON.stringify(form)!==JSON.stringify({...defaultBrand,...saved});
 function update(key,value){setForm(f=>({...f,[key]:value}));}
 async function load(){try{const r=await api('/brand');uploadVersion.current++;setSaved(r.config);setForm({...defaultBrand,...r.config});setRevision(r.revision);setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{load();return()=>{uploadVersion.current++;};},[]);
 async function upload(file){if(!file)return;const version=++uploadVersion.current;setError('');setUploading(true);try{
   if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Choose a PNG, JPEG or WebP image.');
   if(file.size>5*1024*1024)throw new Error('Choose an image smaller than 5 MB.');
   const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Could not read this image.'));reader.readAsDataURL(file);});
   const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(new Error('This image could not be opened.'));image.src=data;});
   const scale=Math.min(1,640/image.naturalWidth,320/image.naturalHeight),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);
   const logo=canvas.toDataURL('image/png');if(logo.length>680000)throw new Error('The optimised logo is too large. Please use a simpler image.');
   if(version===uploadVersion.current)update('logo',logo);
 }catch(e){if(version===uploadVersion.current)setError(e.message);}finally{if(version===uploadVersion.current)setUploading(false);if(fileRef.current)fileRef.current.value='';}}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const r=await api('/admin/brand',{method:'PUT',body:{config:form,revision}});setSaved(r.config);setForm({...defaultBrand,...r.config});setRevision(r.revision);onSaved(r.config);notify('Brand saved. Your company workspace now uses this appearance.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className='brand-settings'><div className='section-heading'><div><h2>Brand & appearance</h2><p className='muted'>Make this meeting workspace feel like your company.</p></div><span className='brand-save-state'>{dirty?'Unsaved changes':'Saved appearance'}</span></div>
 {user.demo&&<p className='notice neutral'>Sample workspace: try the controls and preview. Saving is available in your company workspace.</p>}
 {error&&<div role='alert' className='notice warm'><span>{error}</span>{revision!==null&&<Button type='button' onClick={load} disabled={busy||uploading}>Reload saved settings</Button>}</div>}
 {revision===null?<Button onClick={load}>Reload brand settings</Button>:<form onSubmit={save} className='brand-layout'><div className='brand-controls'><fieldset disabled={busy||uploading}>
 <section className='brand-card'><h3>Identity</h3><Field label='Platform name'><input value={form.name} onChange={e=>update('name',e.target.value)} required maxLength={40}/></Field><Field label='Tagline' hint='Shown on the sign-in screen when this installation hosts one company.'><input value={form.tagline} onChange={e=>update('tagline',e.target.value)} maxLength={100}/></Field>
 <div className='brand-logo-upload'>{form.logo?<img src={form.logo} alt='Uploaded logo preview'/>:<Waveform size={38}/>}<div><strong>Platform logo</strong><p>PNG, JPEG or WebP, up to 5 MB. Transparent PNG works best. Optimised for the workspace when uploaded.</p><div className='button-row'><Button type='button' icon={UploadSimple} onClick={()=>fileRef.current.click()}>{uploading?'Reading logo…':form.logo?'Replace logo':'Upload logo'}</Button>{form.logo&&<Button type='button' onClick={()=>setForm(f=>({...f,logo:null,showName:true}))}>Remove logo</Button>}</div><input ref={fileRef} type='file' accept='image/png,image/jpeg,image/webp' aria-label='Upload platform logo' hidden onChange={e=>upload(e.target.files?.[0])}/></div></div>
 {form.logo&&<><Field label={'Logo width: '+form.logoWidth+' px'}><input type='range' min={48} max={160} value={form.logoWidth} onChange={e=>update('logoWidth',Number(e.target.value))}/></Field><label className='checkbox'><input type='checkbox' checked={form.showName} onChange={e=>update('showName',e.target.checked)}/>Show the platform name with the logo</label></>}
 </section><section className='brand-card'><h3>Colour tone</h3><div className='brand-palettes'>{palettes.map(p=><button key={p.name} type='button' onClick={()=>setForm(f=>({...f,accent:p.accent,sidebar:p.sidebar,background:p.background,link:p.link}))}><span style={{background:p.accent}}/>{p.name}</button>)}</div><div className='brand-color-grid'>{[['accent','Primary buttons'],['sidebar','Sidebar'],['background','Workspace background'],['link','Links & accents']].map(([key,label])=><Field key={key} label={label}><div className='brand-color-input'><input type='color' aria-label={label+' colour'} value={form[key]} onChange={e=>update(key,e.target.value)}/><input aria-label={label+' hex'} value={form[key]} pattern='#[0-9a-fA-F]{6}' required maxLength={7} onChange={e=>update(key,e.target.value)}/></div></Field>)}</div><small>Button and navigation text adjust automatically for readability. Status colours keep their meaning.</small></section>
 <section className='brand-card'><h3>Typography & details</h3>{[['bodyFont','Body font'],['headingFont','Heading font']].map(([key,label])=><Field key={key} label={label}><select value={form[key]} onChange={e=>update(key,e.target.value)}>{Object.entries(fonts).map(([id,f])=><option key={id} value={id}>{f.label}</option>)}</select></Field>)}<small>Inter is bundled. Other fonts use the device’s installed fonts with Chinese fallbacks.</small><Field label={'Corner radius: '+form.radius+' px'}><input type='range' min={0} max={16} value={form.radius} onChange={e=>update('radius',Number(e.target.value))}/></Field></section>
 </fieldset><div className='brand-actions'><Button primary icon={FloppyDisk} disabled={busy||uploading||user.demo||!dirty} type='submit'>{busy?'Saving…':'Save brand'}</Button><Button type='button' disabled={busy||uploading||!dirty} onClick={()=>{setForm({...defaultBrand,...saved});setError('');}}>Discard edits</Button><Button type='button' icon={ArrowCounterClockwise} disabled={busy||uploading} onClick={()=>setForm({...defaultBrand})}>Restore defaults</Button></div><p className='small muted'>Defaults are previewed first; click Save brand to apply. Saved changes affect this company. With a single company, its brand also appears at sign-in. Word and PDF layouts stay controlled by your document templates.</p></div>
 <BrandPreview form={form}/></form>}</div>;
}
function BrandPreview({form}){
 const valid={...form};for(const key of ['accent','sidebar','background','link'])if(!/^#[0-9a-f]{6}$/i.test(valid[key]))valid[key]=defaultBrand[key];
 return <aside className='brand-preview-wrap'><span className='eyebrow'>LIVE PREVIEW</span><div className='brand-preview' style={brandVariables(valid)}><div className='brand-preview-nav'><BrandMark config={valid}/><span>Meeting workspace</span><div>Today</div><div className='active'>Minutes</div><div>Administration</div></div><div className='brand-preview-main'><span className='eyebrow'>{form.tagline||'MEETING WORKSPACE'}</span><h2>Every meeting,<br/>a clear record.</h2><p>Review the discussion and turn decisions into action.</p><p>會議紀錄 · 清晰記錄每項決定</p><button className='button primary' type='button'>Prepare minutes</button><div className='brand-preview-document'><span className='brand-preview-status'><CheckCircle/>Ready for review</span><h3>Project coordination</h3><p>A shared understanding of progress, decisions and next steps.</p><a href='#brand-preview' onClick={e=>e.preventDefault()}>View transcript →</a></div></div></div><p className='small muted'>Preview only until you save.</p>{contrast(valid.link,'#ffffff')<4.5&&<p className='notice warm'>This link colour may be hard to read on white cards. Choose a darker colour for better contrast.</p>}</aside>;
}
