import React,{useEffect,useState} from 'react';
import {api,allowed} from './api';
import {Modal,Field,Button} from './ui';
import {DirectCaptureSetup} from './DirectCaptureSetup';
const Link=({href,children})=><a href={href} target='_blank' rel='noreferrer'>{children} ↗</a>;
export function CaptureSetup({platform,onClose,notify,onSaved}) {
 const [info,setInfo]=useState(null),[view,setView]=useState('recall'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{api(`/admin/capture/${platform}/method`).then(r=>{setInfo(r);setView(r.method);}).catch(e=>setError(e.message));},[platform]);
 async function choose(){setBusy(true);setError('');try{await api(`/admin/capture/${platform}/method`,{method:'PUT',body:{method:view}});setInfo(i=>({...i,method:view}));await onSaved();notify(`Selected ${view==='direct'?'direct integration':'Recall.ai'} for new ${platform} assignments. Complete its setup before capture.`);}catch(e){setError(e.message);}finally{setBusy(false);}}
 if(!info)return <Modal title={`${platform} capture — configuration`} wide onClose={onClose}><p role={error?'alert':undefined}>{error||'Loading capture methods…'}</p></Modal>;
 const picker=<div className='capture-method-picker'><Field label='Configuration method'><select value={view} onChange={e=>setView(e.target.value)}><option value='recall'>Recall.ai — managed meeting bot</option><option value='direct'>{platform==='Teams'?'Direct Teams — Azure Windows media worker':'Direct Zoom — RTMS receiver (no participant bot)'}</option></select></Field><p>Currently selected: <strong>{info.method==='direct'?'Direct integration':'Recall.ai'}</strong>. Settings for both methods are retained. Changing panels discards unsaved edits.</p>{view!==info.method&&<Button primary disabled={busy||info.sample} onClick={choose}>{view==='direct'?'Use direct integration':'Use Recall.ai'}</Button>}{error&&<p role='alert'>{error}</p>}</div>;
 const props={platform,onClose,notify,onSaved,methodPicker:picker};
 return view==='direct'?<DirectCaptureSetup {...props}/>:<RecallCaptureSetup {...props}/>;
}
function RecallCaptureSetup({platform,onClose,notify,onSaved,methodPicker}) {
 const [info,setInfo]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({region:'us-west-2',publicBaseUrl:'',botName:'AI Minutes',notice:'AI Minutes is recording this meeting to prepare a transcript and draft minutes. Please tell the host if you do not consent.',transcriptionProvider:'recall',secret:'',webhookSecret:'',enabled:false,acknowledged:false});
 const update=(key,value)=>setForm(f=>({...f,[key]:value}));
 async function load(initial=false){const r=await api(`/admin/capture/${platform}`);setInfo(r);if(initial)setForm(f=>({...f,...r.config,transcriptionProvider:'recall',enabled:r.enabled,acknowledged:!!r.has_secret}));return r;}
 useEffect(()=>{load(true).catch(e=>setError(e.message));},[platform]);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await api(`/admin/capture/${platform}`,{method:'PUT',body:form});setForm(f=>({...f,secret:'',webhookSecret:''}));await load();await onSaved();notify('Capture configuration saved. Complete both connection checks before sending a bot.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function test(){setBusy(true);setError('');try{const r=await api(`/admin/capture/${platform}/test`,{method:'POST'});await load();await onSaved();notify(r.message);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const copySource=platform==='Teams'?'Zoom':'Teams';
 async function copyFromOther(){setBusy(true);setError('');try{await api(`/admin/capture/${platform}/copy-from/${copySource}`,{method:'POST'});const r=await api(`/admin/capture/${platform}`);setInfo(r);setForm(f=>({...f,...r.config,secret:'',webhookSecret:'',enabled:r.enabled,acknowledged:!!r.has_secret}));await onSaved();notify(`Copied ${copySource} Recall.ai settings. Add and verify the separate ${platform} webhook endpoint before sending a bot.`);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const dashboard=`https://${form.region}.recall.ai/dashboard`,callback=info?.webhookPath?`${form.publicBaseUrl.replace(/\/$/,'')}${info.webhookPath}`:'';
 return <Modal title={`${platform} minutes taker — setup`} wide onClose={onClose}>
 {methodPicker}
 <p>A named participant joins and records the meeting audio. The transcription provider is selected automatically by the capture method.</p>
 <div className='notice warm'><span>Capture method: <strong>Recall.ai managed meeting bot</strong>. A separate Recall account and service charges are required. Meeting links and audio are processed by Recall. Recall transcription can retain meeting participant labels when the platform supplies usable speaker data.</span></div>
 <div className='capture-checks' aria-live='polite'><span>API key: <strong>{info?.checked_at?'Verified':'Not checked'}</strong></span><span>Callback: <strong>{info?.webhook_checked_at?'Verified':'Not received'}</strong></span><span>Assignments: <strong>{info?.enabled&&info?.checked_at&&info?.webhook_checked_at?'Ready':'Not ready'}</strong></span></div>
 {error&&<div role='alert' className='notice warm'>{error}</div>}{info?.sample&&<p className='notice neutral'>Sample workspace: read the guide here. Save credentials, test connections and send bots from your company workspace.</p>}
 {!info?.sample&&<div className='notice neutral'><p>Reuse the shared Recall.ai workspace settings from {copySource}. The API key, verification secret, region, public callback base URL, participant name and recording notice are copied securely; this {platform} webhook endpoint remains distinct and must still be added and verified in Recall.ai.</p><Button type='button' disabled={busy} onClick={copyFromOther}>Copy from {copySource} (Recall.ai) configuration</Button></div>}
 <form onSubmit={save} className='capture-setup'><ol className='setup-steps'>
 <li><h3>Create your capture-service workspace</h3><p>Open <Link href='https://www.recall.ai/'>Recall.ai</Link>, create or sign in to your account, and confirm billing and meeting-bot access. Choose your workspace region below. Use that same region for API keys and webhooks.</p>
 <Field label='Recall workspace region'><select value={form.region} onChange={e=>update('region',e.target.value)}><option value='us-west-2'>US West — us-west-2</option><option value='us-east-1'>US East — us-east-1</option><option value='eu-central-1'>Europe — eu-central-1</option><option value='ap-northeast-1'>Japan — ap-northeast-1</option></select></Field></li>
 <li><h3>Add the API key and participant name</h3><p>Open <Link href={`${dashboard}/developers/api-keys`}>Developers → API keys</Link>. Create an API key and workspace verification secret. Paste the API key here. These are Recall credentials, not Microsoft, Zoom, ElevenLabs or Minutes AI credentials.</p>
 <Field label='Recall API key' hint={info?.has_secret?'Saved and encrypted. Leave blank to keep it.':'Stored encrypted on this server.'}><input type='password' autoComplete='new-password' value={form.secret} onChange={e=>update('secret',e.target.value)} required={!info?.has_secret}/></Field>
 <Field label='Minutes taker participant name'><input value={form.botName} onChange={e=>update('botName',e.target.value)} required maxLength={100}/></Field>
 <Field label='Meeting chat recording notice'><textarea value={form.notice} onChange={e=>update('notice',e.target.value)} required minLength={20} maxLength={500} rows={3}/></Field></li>
 <li><h3>Transcription preference</h3><div className='notice neutral'><strong>Remote meeting joined by this Recall.ai bot: Recall.ai transcription</strong><br/>Recall creates the post-meeting transcript with participant attribution where Teams or Zoom supplies usable speaker data. It adds Recall transcription charges and does not need an ElevenLabs key for this Recall capture.<br/><br/><strong>Phone or browser microphone recording: ElevenLabs transcription</strong><br/>A local recording is uploaded to this platform, then ElevenLabs transcribes it and Minutes AI prepares the draft. Direct/self-hosted remote receivers also use ElevenLabs because they do not pass through Recall.</div></li>
 <li><h3>Connect the callback address</h3><p>This app has a callback-only listener on <strong>port 5001</strong>. Keep this PC, Docker and the callback connection running throughout meetings and processing.</p>
 <ol><li>Use your approved reverse proxy or follow the <Link href='https://ngrok.com/docs/getting-started/'>ngrok setup guide</Link>. Forward a stable public HTTPS hostname to <code>http://localhost:5001</code>. Expose this callback listener only; the main application stays on port 5000.</li><li>For ngrok, install the official client and run the authentication command shown in your ngrok account. Then run <code>ngrok http 5001</code>. Keep that terminal running and use your account’s stable HTTPS domain.</li><li>Paste the public base URL below. Localhost and private Tailscale addresses cannot receive Recall callbacks.</li></ol>
 <Field label='Public callback base URL' hint='Example: https://your-assigned-domain.ngrok-free.app — no path.'><input type='url' value={form.publicBaseUrl} onChange={e=>update('publicBaseUrl',e.target.value)} required placeholder='https://your-public-domain'/></Field>
 <p>Open <Link href={`${dashboard}/webhooks`}>Recall → Webhooks</Link> → Add endpoint. Copy this complete endpoint URL:</p><Field label={`${platform} webhook endpoint`}><input readOnly value={callback}/></Field>
 <p>Subscribe to these events (or bot.* plus recording and transcript events):</p><code className='setup-code'>bot.joining_call · bot.in_waiting_room · bot.in_call_not_recording · bot.in_call_recording · bot.recording_permission_denied · bot.call_ended · bot.done · bot.fatal · recording.done · recording.failed · transcript.done · transcript.failed</code>
 <Field label='Webhook verification secret' hint={info?.has_webhook_secret?'Saved and encrypted. Leave blank to retain it.':'Paste the whsec_ value from the same Recall workspace.'}><input type='password' autoComplete='new-password' value={form.webhookSecret} onChange={e=>update('webhookSecret',e.target.value)} required={!info?.has_webhook_secret}/></Field>
 <p>Accounts created on or after 15 December 2025 use the workspace verification secret from API keys. Older accounts use the dashboard endpoint’s signing secret. <Link href='https://docs.recall.ai/docs/authenticating-requests-from-recallai'>Verification-secret guide</Link></p></li>
 <li><h3>Prepare {platform} and participant consent</h3>{platform==='Teams'?<ol><li>Copy the complete Teams join link from the meeting invitation.</li><li>Confirm with your Teams administrator that the approved meeting policy permits this bot as an external/anonymous participant. If sign-in is mandatory, follow <Link href='https://docs.recall.ai/docs/setting-up-signed-in-bots-for-microsoft-teams'>Recall’s signed-in Teams setup</Link>. Signed-in bots use the account’s display name.</li><li>The host joins first and admits the configured bot from the lobby. Admission alone does not mean recording has started. Normal chat notices are unavailable in Teams channel meetings, so notify participants directly.</li></ol>:<ol><li>Copy the full Zoom invitation link, including its passcode parameter if present.</li><li>Standard Zoom meetings are supported by Recall without a separate Zoom app setup. See the current <Link href='https://docs.recall.ai/docs/zoom-overview'>Zoom setup and limitations</Link>. Begin with a standard meeting; sign-in or registration-required meetings may require additional provider setup.</li><li>The host starts the meeting, admits the named bot, and grants recording permission when requested. This connector does not bypass the waiting room or implement ZAK/OBF token callbacks.</li></ol>}
 <p>Tell participants before recording and confirm consent for each meeting. The chat notice is an additional reminder. This setup does not change tenant policies or bypass the host.</p></li>
 <li><h3>Save and verify the connection</h3><p>Check the acknowledgement and save below. Then click <strong>Test API connection</strong>. In Recall’s webhook endpoint page, send a signed test event. Click <strong>Refresh checks</strong> here; both checks must show Verified.</p>
 <label className='checkbox consent'><input type='checkbox' checked={form.acknowledged} onChange={e=>update('acknowledged',e.target.checked)} required/>I authorise the configured capture service to receive assigned meeting links/audio and understand its separate charges.</label>
 <label className='checkbox consent'><input type='checkbox' checked={form.enabled} onChange={e=>update('enabled',e.target.checked)}/>Enable {platform} capture for new assignments once both checks pass.</label>
 <div className='button-row'><Button primary disabled={busy||info?.sample||!info} type='submit'>{busy?'Working…':'Save configuration'}</Button><Button type='button' disabled={busy||info?.sample||!info?.has_secret} onClick={test}>Test API connection</Button><Button type='button' disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Refresh checks</Button></div>
 <small>Save edits before testing. Changing region, callback URL or secrets resets both checks. Configure Teams and Zoom separately, even if they share a Recall workspace.</small></li>
 <li><h3>Run your first meeting</h3><ol><li>Confirm Minutes AI is configured under Administration → Connections.</li><li>Open Today → Add a minutes taker. Paste the link, choose the time/team/template, confirm consent and save. Ready connections dispatch or schedule a bot automatically. For an older “Setup required” assignment, open its workspace and click <strong>Send minutes taker</strong>.</li><li>Schedule at least 10 minutes ahead when possible; immediate joining depends on provider capacity. Have the host admit the bot and grant recording permission.</li><li>Only <strong>Capturing</strong> confirms active recording. Use <strong>Stop minutes taker</strong> to request that it leave.</li><li>After the meeting: audio download → Recall participant-attributed transcript → AI draft → review. Chinese remains Traditional Chinese, and speaker names can be corrected.</li></ol><p>Start with a short consented test meeting. Recall capture and transcription fees are not included in the platform’s calculated API cost.</p></li>
 </ol><details><summary>Troubleshooting and self-hosted alternatives</summary><ul><li><strong>API check fails:</strong> check the key, region and provider account access.</li><li><strong>Callback not received:</strong> check port 5001, tunnel, exact endpoint URL, event subscriptions and signing secret.</li><li><strong>Waiting in lobby:</strong> the host must admit the named bot.</li><li><strong>Joined, not recording:</strong> check host permission and Recall status.</li><li><strong>Dispatch uncertain:</strong> check Recall for an existing bot; recover its ID in the workspace instead of creating a duplicate.</li><li><strong>Import failed:</strong> retry import. Multiple recording parts or audio above 250 MB require reviewing/downloading parts in Recall and importing them manually.</li></ul><p>Native self-hosted capture is a separate deployment, not activated by these fields. Teams needs a C#/.NET media bot on Azure Windows. Zoom needs an authorised media/participant integration. <Link href='https://learn.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots'>Teams native requirements</Link> · <Link href='https://developers.zoom.us/docs/rtms/'>Zoom RTMS docs</Link></p><p><Link href='https://docs.recall.ai/reference/bot_create'>Bot API</Link> · <Link href='https://docs.recall.ai/docs/bot-status-change-events'>Status events</Link> · <Link href='https://docs.recall.ai/docs/how-to-get-mixed-audio-async'>Recording retrieval</Link></p></details>
 </form><footer className='modal-actions'><Button onClick={onClose}>Close guide</Button></footer></Modal>;
}
export function RemoteCapture({meeting:m,user,refresh,notify}) {
 const [busy,setBusy]=useState(false),[botId,setBotId]=useState('');
 if(!['Teams','Zoom'].includes(m.platform))return null;
 const s=m.capture,direct=(s?.method||m.captureMethod)==='direct';
 async function run(action){setBusy(true);try{await api(`/meetings/${m.id}/capture/${action}`,{method:'POST',body:{revision:m.revision,...(action==='recover'?{botId}:{})}});await refresh();notify(action==='start'?'Minutes taker queued. Wait for provider admission and recording confirmation.':action==='stop'?'Stop requested. Waiting for provider confirmation.':action==='recall-transcribe'?'Recall.ai transcription queued. A new participant-attributed transcript and draft will follow.':'Capture request saved.');}catch(e){notify(e.message);}finally{setBusy(false);}}
 const descriptions={SETUP_REQUIRED:`Complete Administration → Connections → ${m.platform} setup, then start capture.`,SCHEDULED:'Queued or scheduled. Recording has not started.',JOINING_CALL:'The minutes taker is connecting to the meeting.',WAITING_FOR_HOST:'The direct receiver is waiting for the authorised Zoom RTMS app to start in this meeting.',WAITING_FOR_ADMISSION:'The host must admit the named minutes taker from the lobby.',IN_CALL_NOT_RECORDING:'Connected, but not recording. Check recording permission with the host.',CAPTURING:'The capture service confirms that recording is active.',PROCESSING_RECORDING:'The meeting ended. Waiting for the completed audio to import.',STOPPING_CAPTURE:'Stop requested. Waiting for capture service confirmation.'};
 const canRecallTranscribe=!direct&&s?.recording_id&&s?.imported_at&&s.transcription_provider!=='recall'&&m.transcripts?.some(t=>String(t.source||'').startsWith('ElevenLabs'));
 return <div className='remote-capture-panel'><strong>{m.platform} remote capture · {direct?'Direct integration':'Recall.ai'}</strong><p>{descriptions[m.status]||'Recording and processing status appears above.'}</p>{!direct&&<small>Final transcript: {s?.transcription_provider==='recall'?'Recall.ai participant attribution':'ElevenLabs voice diarization'}</small>}{direct&&m.platform==='Zoom'&&<p>Zoom RTMS receives authorised meeting audio without a named participant bot.</p>}{s?.bot_id&&<small>{direct?'Worker session ID':'Recall bot ID'}: {s.bot_id}</small>}
 {allowed(user,'MEETING_ORGANIZER')&&<div className='button-row'>{(!s||s.state==='REJECTED')&&['DRAFT','SETUP_REQUIRED','FAILED'].includes(m.status)&&<Button primary disabled={busy||user.demo} onClick={()=>run('start')}>{direct?'Start direct capture':s?'Retry minutes taker':'Send minutes taker'}</Button>}{s&&!s.imported_at&&!['CANCELLED','ENDED','fatal'].includes(s.state)&&<Button disabled={busy||user.demo} onClick={()=>run('stop')}>{s.stop_requested?'Retry stop request':direct?'Stop capture':'Stop minutes taker'}</Button>}{s?.recording_id&&!s.imported_at&&m.status==='FAILED'&&<Button disabled={busy} onClick={()=>run('import')}>Retry recording import</Button>}{canRecallTranscribe&&<Button disabled={busy||user.demo} onClick={()=>run('recall-transcribe')}>Re-transcribe with Recall speaker names</Button>}</div>}
 {canRecallTranscribe&&<small className='capture-transcript-note'>Recall will create a new transcript and draft from this completed recording. Its transcription charge applies; review the new draft before approval.</small>}
 {s&&!s.bot_id&&['UNKNOWN','DISPATCHING'].includes(s.state)&&allowed(user,'MEETING_ORGANIZER')&&(direct?<Button disabled={busy||s.stop_requested} onClick={()=>run('recover')}>Retry worker dispatch</Button>:<div><Field label='Existing Recall bot ID' hint='Copy the bot ID from the Recall dashboard. Recovery verifies that it belongs to this assignment.'><input value={botId} onChange={e=>setBotId(e.target.value)}/></Field><Button disabled={busy||!botId} onClick={()=>run('recover')}>Recover bot ID</Button></div>)}
 <small>{direct?'Capture uses your configured worker. Hosting and provider charges may apply.':'Capture uses Recall.ai; its fees are billed separately.'} Host authorisation and participant consent are required.</small></div>;
}
