import React,{useEffect,useState} from 'react';
import {api} from './api';
import {Modal,Field,Button} from './ui';
const Link=({href,children})=><a href={href} target='_blank' rel='noreferrer'>{children} ↗</a>;
export function DirectCaptureSetup({platform,onClose,notify,onSaved,methodPicker}) {
 const teams=platform==='Teams';
 const [info,setInfo]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({workerUrl:teams?'http://host.docker.internal:8010':'http://host.docker.internal:8020',tenantId:'',clientId:'',accountId:'',botName:teams?'AI Minutes':'AI Minutes RTMS',notice:'This meeting audio is being processed to prepare a transcript and draft minutes. Please tell the host if you do not consent.',secret:'',enabled:false,acknowledged:false});
 const update=(key,value)=>setForm(f=>({...f,[key]:value}));
 async function load(initial=false){const r=await api(`/admin/capture/${platform}/direct`);setInfo(r);if(initial)setForm(f=>({...f,...r.config,enabled:r.enabled,acknowledged:!!r.has_secret}));}
 useEffect(()=>{load(true).catch(e=>setError(e.message));},[platform]);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await api(`/admin/capture/${platform}/direct`,{method:'PUT',body:form});setForm(f=>({...f,secret:''}));await load();await onSaved();notify('Direct settings saved. Test the worker, then select this method for new assignments.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function test(){setBusy(true);setError('');try{const r=await api(`/admin/capture/${platform}/direct/test`,{method:'POST'});await load();await onSaved();notify(r.message);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <Modal title={`${platform} capture — configuration`} wide onClose={onClose}>
 {methodPicker}
 <div className='notice neutral'><span><strong>{teams?'Direct Teams · Azure Windows media worker':'Direct Zoom · RTMS receiver'}</strong><br/>{teams?'A named bot joins through your own Microsoft application. Azure hosting and ongoing worker maintenance apply.':'Receives host-authorised audio through a Zoom app. It does not join as a named participant. Zoom RTMS credits and receiver hosting apply.'} No Recall.ai account is used for this method. ElevenLabs and Minutes AI charges remain.</span></div>
 <div className='notice warm'><span><strong>Separate worker deployment required.</strong> The platform connector can save settings, test a compatible worker, dispatch sessions and import recordings. The native {teams?'Microsoft media bot':'Zoom RTMS receiver'} is not bundled in this Docker app. Saving settings does not deploy it; a stock SDK sample must be adapted to the worker contract below.</span></div>
 <div className='capture-checks'><span>Worker: <strong>{info?.checked_at?'Verified':'Not verified'}</strong></span><span>Direct capture: <strong>{info?.enabled&&info?.checked_at?'Ready when selected':'Setup required'}</strong></span></div>
 {error&&<div role='alert' className='notice warm'>{error}</div>}
 {info?.sample&&<p className='notice neutral'>Sample workspace: the guide is available, but connection changes and worker requests are disabled.</p>}
 <form className='capture-setup' onSubmit={save}><ol className='setup-steps'>
 <li><h3>{teams?'Register your Microsoft application':'Create and authorise a Zoom RTMS app'}</h3>
 {teams?<ol><li>Open <Link href='https://entra.microsoft.com/'>Microsoft Entra admin centre</Link> → Identity → Applications → App registrations → New registration. Register a single-tenant application for the minutes taker.</li><li>On Overview, copy Directory (tenant) ID and Application (client) ID into the fields below.</li><li>Follow <Link href='https://learn.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/registering-calling-bot'>Microsoft’s calling-bot registration guide</Link>. Configure the Teams channel, calling endpoint and calling permissions. For meeting audio, your administrator must review and grant the required application permissions, including Calls.AccessMedia.All and the appropriate group-call join permission.</li><li>Configure the application certificate/secret on the Azure media worker. Keep it off the browser and out of these worker API-key fields.</li></ol>:<ol><li>Open <Link href='https://marketplace.zoom.us/'>Zoom App Marketplace</Link> → Develop → Build App. Use the app type supported by <Link href='https://developers.zoom.us/docs/rtms/meetings/quickstart/'>Zoom’s RTMS setup guide</Link>; enable RTMS and the meeting audio scope.</li><li>Copy the app Client ID and your Zoom account ID below. Store the Client Secret and webhook Secret Token on the receiver server.</li><li>Enable subscriptions for meeting.rtms_started and meeting.rtms_stopped. Set their endpoint to the receiver’s public HTTPS webhook URL and complete Zoom endpoint validation.</li><li>Install/authorise the app for the participating Zoom user or account. Enable sharing real-time meeting content with apps. Enable auto-start or have the host start this app during the meeting. Obtain the required RTMS credits.</li></ol>}
 {teams&&<Field label='Microsoft tenant ID'><input required value={form.tenantId} onChange={e=>update('tenantId',e.target.value)} placeholder='Directory (tenant) ID'/></Field>}
 <Field label={teams?'Microsoft application (client) ID':'Zoom app client ID'}><input required value={form.clientId} onChange={e=>update('clientId',e.target.value)}/></Field>
 {!teams&&<Field label='Zoom account ID' hint='The account that owns the authorised RTMS application; not a meeting ID.'><input required value={form.accountId} onChange={e=>update('accountId',e.target.value)}/></Field>}</li>
 <li><h3>{teams?'Deploy an Azure Windows media worker':'Deploy your RTMS receiver'}</h3>
 {teams?<ol><li>Provision an Azure Windows Server supported by Microsoft’s media SDK. Production media workers require Azure Windows hosting, public connectivity and valid certificates; this Linux app container cannot host that SDK.</li><li>Have your deployment developer implement the compatible worker API below around the <Link href='https://github.com/microsoftgraph/microsoft-graph-comms-samples'>Microsoft Graph communications samples</Link>. Configure the application identity, certificate, callback hostname and media ports from <Link href='https://learn.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots'>Microsoft’s hosting requirements</Link>.</li><li>Before persisting audio, the worker must successfully report recording status using <Link href='https://learn.microsoft.com/en-us/graph/api/call-updaterecordingstatus?view=graph-rest-1.0'>updateRecordingStatus</Link> and satisfy the applicable Teams recording-policy requirements. Only then may it report active recording.</li><li>Give the worker a private control API protected by a long random API key. The public Microsoft callback/media endpoints are separate from this control API.</li></ol>:<ol><li>Have your deployment developer build the receiver using the official <Link href='https://developers.zoom.us/docs/rtms/meetings/quickstart/'>Zoom RTMS SDK quickstart</Link> and implement the compatible worker API below. It can run on your own server or a separate Docker service.</li><li>Verify Zoom webhook signatures and timestamps, match the authorised account and assigned meeting, then connect to its RTMS stream. Collect mixed audio into a final WAV or MP3 recording.</li><li>Arm only meetings explicitly assigned in this platform. Never capture every account meeting just because an event arrives. Keep assignment and recording data durable across restarts.</li><li>Expose the receiver’s Zoom webhook over HTTPS. Protect its separate control API with a long random API key. This control URL is what you enter below.</li></ol>}
 <p><strong>Deployment handoff:</strong> the SDK supplies media access; it does not supply this platform’s control API. Your worker must implement and pass the contract below before capture can be enabled.</p></li>
 <li><h3>Connect the worker to this platform</h3><p>Enter the control API origin and its API key. This key authenticates AI Minutes to your worker; it is not the Microsoft application secret or Zoom Client Secret.</p>
 <Field label='Worker control API base URL' hint={teams?'Example: https://teams-worker.your-company.com':'Example: http://host.docker.internal:8020 for a receiver on this PC'}><input type='url' required value={form.workerUrl} onChange={e=>update('workerUrl',e.target.value)}/></Field>
 <Field label='Worker API key' hint={info?.has_secret?'Encrypted key saved. Leave blank to retain it.':'Create the key on the worker, then paste the same value here.'}><input type='password' autoComplete='new-password' required={!info?.has_secret} value={form.secret} onChange={e=>update('secret',e.target.value)}/></Field>
 <p>For an Azure/server URL, add its exact origin to <code>CAPTURE_WORKER_ALLOWED_ORIGINS</code> in this project’s <code>.env</code>, then run <code>docker compose up -d app</code>. Keep any existing origins in the comma-separated list. Local ports 8010 and 8020 on host.docker.internal are already permitted. Docker’s localhost refers to its container; use host.docker.internal for a service on this PC. Use HTTPS for connections over untrusted networks.</p></li>
 <li><h3>Set the recording identity and notice</h3>
 <Field label={teams?'Minutes taker participant name':'RTMS session label'}><input required maxLength={100} value={form.botName} onChange={e=>update('botName',e.target.value)}/></Field>
 <Field label='Recording notice for the worker'><textarea required minLength={20} maxLength={500} rows={3} value={form.notice} onChange={e=>update('notice',e.target.value)}/></Field>
 <p>{teams?'The host must admit the bot and the tenant must permit recording.':'The host/user must authorise the RTMS app. Arming a session here does not independently enter a meeting or bypass account permissions.'} Tell participants before recording and confirm consent for every assignment.</p></li>
 <li><h3>Save, test and select this method</h3><p>Save these settings, then click <strong>Test direct worker</strong>. The test checks protocol, application/account identity, readiness and required capabilities; it does not record a meeting. Finally click <strong>Use direct integration</strong> at the top. Existing Recall credentials remain saved.</p>
 <label className='checkbox consent'><input type='checkbox' required checked={form.acknowledged} onChange={e=>update('acknowledged',e.target.checked)}/>I authorise this worker to process assigned meeting links and audio and understand the hosting/provider costs.</label>
 <label className='checkbox consent'><input type='checkbox' checked={form.enabled} onChange={e=>update('enabled',e.target.checked)}/>Enable direct capture after verification and selection.</label>
 <div className='button-row'><Button primary type='submit' disabled={busy||!info||info.sample}>{busy?'Working…':'Save direct configuration'}</Button><Button type='button' disabled={busy||!info?.has_secret||info?.sample} onClick={test}>Test direct worker</Button><Button type='button' disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Refresh checks</Button></div>
 <small>Saving either configuration does not change the selected method. Switching methods is blocked during active capture. Changes to worker address, identity or key reset verification.</small></li>
 <li><h3>Run a short consented test</h3><ol><li>Configure ElevenLabs and Minutes AI. Create a Teams/Zoom assignment with the correct link, time and template.</li><li>{teams?'The worker schedules the named bot. Have the host admit it and confirm recording is permitted.':'The receiver arms this assignment. Start the authorised RTMS app in that meeting, or use the configured auto-start setting. “Waiting for host” means audio has not started.'}</li><li>Confirm the workspace reaches <strong>Capturing</strong>, then use <strong>Stop capture</strong> or end the meeting.</li><li>The platform retrieves the final recording from the worker, transcribes it and generates draft minutes. Check the Traditional Chinese text, speaker names and source evidence before approval.</li></ol></li>
 </ol></form>
 <details className='worker-contract'><summary>Worker API contract — for your deployment developer</summary><p>Protocol: <code>ai-minutes-capture/v1</code>. Every request uses <code>Authorization: Bearer WORKER_API_KEY</code>. This is the platform’s adapter contract, not a native Microsoft/Zoom endpoint.</p>
 <ul><li><code>GET /v1/health</code>: return protocol, platform, ready, clientId, {teams?'tenantId':'accountId'} and capabilities. Required capabilities: audio, schedule, stop, idempotentSessions and {teams?'recordingStatus':'rtms'} — all true only when implemented and provider setup is ready.</li><li><code>PUT /v1/sessions/MEETING_UUID</code>: create or return the same session, atomically keyed by meeting UUID. Receive meetingUrl, scheduledAt, durationMinutes, consent, displayName and notice. Never create a duplicate on retry.</li><li><code>GET /v1/sessions/MEETING_UUID</code>: return id, platform, state and updatedAt (ISO timestamp). States: QUEUED, JOINING, WAITING_FOR_ADMISSION, WAITING_FOR_HOST, CONNECTED, RECORDING, PROCESSING, COMPLETED, STOPPED or FAILED.</li><li><code>POST /v1/sessions/MEETING_UUID/stop</code>: idempotently stop only that session, even if dispatch outcome was uncertain. Keep completed audio for import.</li><li><code>GET /v1/sessions/MEETING_UUID/audio</code>: stream the final WAV or MP3. COMPLETED must include audio.mime and audio.bytes. Maximum 250 MB; no redirect or remote download URL.</li></ul><p>Persist sessions and stop requests. Restrict each deployment/API key to the configured tenant/account. Keep native credentials and webhook validation on the worker. Preserve recovered partial audio for manual upload; do not report partial recordings as complete. The platform polls the worker control API, never the provider’s status API.</p></details>
 <footer className='modal-actions'><Button onClick={onClose}>Close guide</Button></footer></Modal>;
}
