import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,randomBytes,createHash} from 'node:crypto';import pg from 'pg';
const base=process.env.TEST_URL||'http://127.0.0.1:5000';const pool=new pg.Pool({connectionString:process.env.DATABASE_URL});
async function request(path,method='GET',body,cookie){const r=await fetch(base+'/api'+path,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});const ct=r.headers.get('content-type')||'';return{status:r.status,data:ct.includes('json')?await r.json():Buffer.from(await r.arrayBuffer()),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
test('authenticated review, immutable approval, export, scopes and rates',async()=>{
 const org=randomUUID(),otherOrg=randomUUID(),admin=randomUUID(),member=randomUUID(),outsider=randomUUID(),unit=randomUUID(),otherUnit=randomUUID(),template=randomUUID();const ids=[org,otherOrg];
 async function session(id){const token=randomBytes(32).toString('hex');await pool.query("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,now()+interval '1 hour')",[createHash('sha256').update(token).digest('hex'),id]);return'minutes_session='+token;}
 try{
 for(const id of ids)await pool.query('INSERT INTO organizations(id,name,demo) VALUES($1,$2,true)',[id,'Automated test '+id]);
 for(const [id,organization,roles] of [[admin,org,['ORG_ADMIN']],[member,org,['MEMBER']],[outsider,otherOrg,['ORG_ADMIN']]])await pool.query('INSERT INTO users(id,org_id,name,email,roles) VALUES($1,$2,$3,$4,$5)',[id,organization,'Test user',id+'@example.invalid',roles]);
 await pool.query("INSERT INTO units(id,org_id,name,kind) VALUES($1,$2,'Test Site','team'),($3,$2,'Restricted','team')",[unit,org,otherUnit]);await pool.query("INSERT INTO templates(id,org_id,name,sections) VALUES($1,$2,'Test template','[]')",[template,org]);await pool.query('UPDATE users SET unit_ids=$2 WHERE id=$1',[member,[unit]]);
 const a=await session(admin),b=await session(member),c=await session(outsider);assert.equal((await request('/meetings')).status,401);
 const body={title:'Integration workflow',joinUrl:'',scheduledAt:new Date().toISOString(),unitId:unit,templateId:template,consent:true};const created=await request('/meetings','POST',body,a);assert.equal(created.status,201,JSON.stringify(created.data));const id=created.data.id;
 assert.equal((await request('/meetings/'+id,'GET',null,c)).status,404);assert.equal((await request('/meetings/'+id,'GET',null,b)).status,200);assert.equal((await request('/admin/users','GET',null,b)).status,403);assert.equal((await request('/meetings','POST',body,b)).status,403);
 const privateM=await request('/meetings','POST',{...body,title:'Restricted meeting',unitId:otherUnit},a);assert.equal((await request('/meetings/'+privateM.data.id,'GET',null,b)).status,404);assert.equal((await request('/meetings','GET',null,b)).data.length,1);
 const segments=[{id:'s1',speaker:'Morgan',start:15,text:'Morgan will issue the report by 2026-09-23.'}];let m=(await request('/meetings/'+id,'GET',null,a)).data;assert.equal((await request('/meetings/'+id+'/transcript','PUT',{segments,revision:m.revision},a)).status,200);m=(await request('/meetings/'+id,'GET',null,a)).data;let doc=m.minutes[0];
 const content={summary:'Report issue agreed.',attendees:['Morgan'],items:[{type:'action',text:'Issue the report.',evidence:'s1',quote:segments[0].text,owner:'Morgan',dueDate:'2026-09-23',verified:false}]};assert.equal((await request('/meetings/'+id+'/minutes','PUT',{content,revision:doc.revision},a)).status,200);assert.equal((await request('/meetings/'+id+'/minutes','PUT',{content,revision:doc.revision},a)).status,409);
 m=(await request('/meetings/'+id,'GET',null,a)).data;assert.equal((await request('/meetings/'+id+'/actions/submit','POST',{revision:m.revision},a)).status,422);content.items[0].verified=true;assert.equal((await request('/meetings/'+id+'/minutes','PUT',{content,revision:m.minutes[0].revision},a)).status,200);
 assert.equal((await request('/meetings/'+id+'/actions/approve','POST',{revision:m.revision},a)).status,409);assert.equal((await request('/meetings/'+id+'/actions/submit','POST',{revision:m.revision},a)).status,200);m=(await request('/meetings/'+id,'GET',null,a)).data;
 assert.equal((await request('/meetings/'+id+'/actions/approve','POST',{revision:m.revision},b)).status,403);assert.equal((await request('/meetings/'+id+'/actions/approve','POST',{revision:m.revision},a)).status,200);m=(await request('/meetings/'+id,'GET',null,a)).data;
 assert.equal((await request('/meetings/'+id+'/minutes','PUT',{content,revision:m.minutes[0].revision},a)).status,409);assert.equal((await request('/meetings/'+id+'/transcript','PUT',{segments,revision:m.revision},a)).status,409);
 const docx=await request('/meetings/'+id+'/export/docx','GET',null,a);assert.equal(docx.status,200);assert.equal(docx.data.subarray(0,2).toString(),'PK');const pdf=await request('/meetings/'+id+'/export/pdf','GET',null,a);assert.equal(pdf.status,200);assert.equal(pdf.data.subarray(0,4).toString(),'%PDF');
 assert.equal((await request('/meetings/'+id+'/actions/reopen','POST',{revision:m.revision},a)).status,200);m=(await request('/meetings/'+id,'GET',null,a)).data;assert.equal(m.minutes.length,2);assert.equal(m.minutes[1].status,'APPROVED');assert.equal(m.minutes[0].content.items[0].verified,false);
 const rate=await request('/admin/rates','POST',{provider:'ElevenLabs',model:'scribe_v2',unit:'audio_minute',usdRate:.01,hkdPerUsd:7.8,effectiveAt:new Date().toISOString()},a);assert.equal(rate.status,201);const recallRate=await request('/admin/rates','POST',{provider:'Recall.ai',model:'meeting_bot',unit:'bot_minute',usdRate:.00833333,hkdPerUsd:7.8,effectiveAt:new Date().toISOString()},a);assert.equal(recallRate.status,201);assert.equal((await request('/admin/rates','GET',null,a)).data.length,2);
 assert.equal((await request('/admin/integrations','PUT',{provider:'ElevenLabs',config:{model:'scribe_v2'},secret:'test-only'},a)).status,403);
 const csrf=await fetch(base+'/api/meetings',{method:'POST',headers:{Cookie:a,Origin:'https://hostile.example','Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal(csrf.status,403);
 }finally{for(const table of ['audit','rate_cards','integrations','oauth_states'])await pool.query(`DELETE FROM ${table} WHERE org_id=ANY($1::uuid[])`,[ids]);await pool.query('DELETE FROM sessions WHERE user_id IN (SELECT id FROM users WHERE org_id=ANY($1::uuid[]))',[ids]);for(const table of ['jobs','usage','minutes','transcripts'])await pool.query(`DELETE FROM ${table} WHERE meeting_id IN (SELECT id FROM meetings WHERE org_id=ANY($1::uuid[]))`,[ids]);for(const table of ['meetings','templates','users','units','organizations'])await pool.query(`DELETE FROM ${table} WHERE ${table==='organizations'?'id':'org_id'}=ANY($1::uuid[])`,[ids]);await pool.end();}
});
