import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,randomBytes,createHash,createHmac} from 'node:crypto';
import {query,tx,pool} from '../../services/api/db.mjs';import {encrypt} from '../../services/api/providers.mjs';
import {queueCapture,queueCaptureStop,processCaptureEvent,runCaptureJob} from '../../services/api/capture.mjs';
const base=process.env.TEST_URL||'http://127.0.0.1:5000';
test('remote capture gates dispatch, verifies callbacks, scopes tenants, preserves lifecycle and imports MP3 to transcription',async()=>{
 const org=randomUUID(),other=randomUUID(),user=randomUUID(),member=randomUUID(),unit=randomUUID(),template=randomUUID(),mid=randomUUID(),bot=randomUUID(),recording=randomUUID();
 const key=randomBytes(32),wh='whsec_'+key.toString('base64'),originalFetch=globalThis.fetch;let savedPath;
 async function session(id){const token=randomBytes(32).toString('hex');await query("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,now()+interval '1 hour')",[createHash('sha256').update(token).digest('hex'),id]);return 'minutes_session='+token;}
 async function request(url,method='GET',body,cookie){const r=await originalFetch(base+'/api'+url,{method,headers:{Cookie:cookie||'','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};}
 try{
  for(const id of [org,other])await query('INSERT INTO organizations(id,name) VALUES($1,$2)',[id,'Remote capture TEST '+id]);
  for(const [id,o,roles] of [[user,org,['ORG_ADMIN']],[member,other,['ORG_ADMIN']]])await query('INSERT INTO users(id,org_id,name,email,roles) VALUES($1,$2,$3,$4,$5)',[id,o,'Capture test',id+'@example.invalid',roles]);
  await query("INSERT INTO units(id,org_id,name,kind) VALUES($1,$2,'Remote test','team')",[unit,org]);await query("INSERT INTO templates(id,org_id,name,sections) VALUES($1,$2,'Test','[]')",[template,org]);
  await query("INSERT INTO meetings(id,org_id,unit_id,owner_id,title,platform,join_url,scheduled_at,template_id,consent,status) VALUES($1,$2,$3,$4,'Synthetic remote test','Teams','https://teams.microsoft.com/l/meetup-join/test',now()+interval '1 hour',$5,true,'SETUP_REQUIRED')",[mid,org,unit,user,template]);
  const a=await session(user),b=await session(member),config={region:'us-west-2',publicBaseUrl:'https://capture.example.com',botName:'TEST Minutes',notice:'This synthetic test is a consented recording.',secret:'synthetic-api-key',webhookSecret:wh,enabled:true,acknowledged:true};
  assert.equal((await request('/admin/capture/Teams','PUT',config,a)).status,200);
  const view=(await request('/admin/capture/Teams','GET',null,a)).data;assert.equal(view.has_secret,true);assert.equal(view.secret,undefined);assert.equal(view.webhook_secret,undefined);assert.equal(view.config.webhookSecret,undefined);
  assert.equal((await request('/admin/capture/Zoom/copy-from/Teams','POST',null,a)).status,200);
  const copied=(await request('/admin/capture/Zoom','GET',null,a)).data;assert.deepEqual(copied.config,{region:config.region,publicBaseUrl:config.publicBaseUrl,botName:config.botName,notice:config.notice,transcriptionProvider:'recall'});assert.equal(copied.has_secret,true);assert.equal(copied.has_webhook_secret,true);assert.equal(copied.checked_at,null);assert.equal(copied.webhook_checked_at,null);assert.equal((await request('/admin/capture/Teams/copy-from/Teams','POST',null,a)).status,400);
  assert.equal((await request(`/meetings/${mid}/capture/start`,'POST',{revision:1},b)).status,404);
  assert.equal((await request(`/meetings/${mid}/capture/start`,'POST',{revision:1},a)).status,409);
  const raw=JSON.stringify({event:'bot.done',data:{bot:{id:randomUUID()},data:{updated_at:new Date().toISOString()}}}),timestamp=String(Math.floor(Date.now()/1000)),eid='msg_'+randomUUID(),signature=createHmac('sha256',key).update(`${eid}.${timestamp}.${raw}`).digest('base64');
  const hook=`http://127.0.0.1:5001/api/capture/recall/${org}/teams`,headers={'Content-Type':'application/json','webhook-id':eid,'webhook-timestamp':timestamp,'webhook-signature':'v1,'+signature};
  assert.equal((await originalFetch(hook,{method:'POST',headers:{...headers,'webhook-signature':'v1,bad'},body:raw})).status,401);
  assert.equal((await originalFetch(hook,{method:'POST',headers,body:raw})).status,202);assert.equal((await originalFetch(hook,{method:'POST',headers,body:raw})).status,202);
  assert.equal((await query('SELECT count(*)::int AS n FROM capture_webhooks WHERE org_id=$1',[org])).rows[0].n,1);
  await query('INSERT INTO integrations(org_id,provider,secret,config) VALUES($1,$2,$3,$4)',[org,'Minutes AI',encrypt('synthetic'),{model:'test'}]);
  await query('UPDATE capture_connections SET checked_at=now() WHERE org_id=$1',[org]);
  let m=(await query('SELECT * FROM meetings WHERE id=$1',[mid])).rows[0];
  await tx(async db=>{assert.equal(await queueCapture(db,m),true);await db.query("UPDATE jobs SET run_at='2100-01-01' WHERE meeting_id=$1",[mid]);});
  await assert.rejects(tx(db=>queueCapture(db,m)),{status:409});
  let calls=0;globalThis.fetch=async(url,options)=>{calls++;assert.match(String(url),/^https:\/\/us-west-2\.recall.ai\/api\/v1\/bot\/$/);assert.equal(options.headers.Authorization,'synthetic-api-key');const body=JSON.parse(options.body);assert.equal(body.metadata.minutes_meeting_id,mid);assert.equal(body.bot_name,'TEST Minutes');return Response.json({id:bot});};
  await runCaptureJob({type:'CAPTURE_CREATE'},m,process.env.DATA_DIR);await runCaptureJob({type:'CAPTURE_CREATE'},m,process.env.DATA_DIR);assert.equal(calls,1);
  await query("UPDATE jobs SET status='COMPLETED' WHERE meeting_id=$1",[mid]);
  const t=Date.now();const event=(name,at=t,orgId=org)=>({org_id:orgId,platform:'Teams',payload:{event:name,data:{bot:{id:bot},data:{updated_at:new Date(at).toISOString()}}}});
  await tx(db=>processCaptureEvent(db,event('bot.in_call_recording',t,other)));assert.equal((await query('SELECT status FROM meetings WHERE id=$1',[mid])).rows[0].status,'SCHEDULED');
  await tx(db=>processCaptureEvent(db,event('bot.in_waiting_room',t)));assert.equal((await query('SELECT status FROM meetings WHERE id=$1',[mid])).rows[0].status,'WAITING_FOR_ADMISSION');
  await tx(db=>processCaptureEvent(db,event('bot.in_call_recording',t+1000)));await tx(db=>processCaptureEvent(db,event('bot.joining_call',t-1000)));assert.equal((await query('SELECT status FROM meetings WHERE id=$1',[mid])).rows[0].status,'CAPTURING');
  await tx(async db=>{await processCaptureEvent(db,{org_id:org,platform:'Teams',payload:{event:'recording.done',data:{bot:{id:bot},recording:{id:recording}}}});await db.query("UPDATE jobs SET run_at='2100-01-01' WHERE meeting_id=$1",[mid]);});
  globalThis.fetch=async(url,options)=>{if(String(url).includes('/recording/'))return Response.json({bot:{id:bot},media_shortcuts:{audio_mixed:{status:{code:'done'},format:'mp3',data:{download_url:'https://synthetic-bucket.s3.amazonaws.com/audio.mp3'}}}});assert.equal(options.headers,undefined);return new Response(Buffer.from('ID3synthetic-test-audio'));};
  await runCaptureJob({type:'CAPTURE_IMPORT'},m,process.env.DATA_DIR,{transcribeAt:new Date('2100-01-01')});m=(await query('SELECT * FROM meetings WHERE id=$1',[mid])).rows[0];savedPath=m.file_path;assert.equal(m.status,'TRANSCRIBING_FINAL');assert.equal(m.mime_type,'audio/mpeg');assert.ok((await query("SELECT 1 FROM jobs WHERE meeting_id=$1 AND type='CAPTURE_RECALL_TRANSCRIBE'",[mid])).rowCount);assert.equal((await query("SELECT config->>'transcriptionProvider' AS provider FROM capture_sessions WHERE meeting_id=$1",[mid])).rows[0].provider,'recall');
  await runCaptureJob({type:'CAPTURE_IMPORT'},m,process.env.DATA_DIR);await tx(db=>processCaptureEvent(db,event('bot.fatal',t+2000)));assert.equal((await query('SELECT status FROM meetings WHERE id=$1',[mid])).rows[0].status,'TRANSCRIBING_FINAL');
  const detail=await request('/meetings/'+mid,'GET',null,a);assert.equal(detail.data.capture.secret,undefined);assert.equal(detail.data.capture.bot_id,bot);
  async function fixture(){const id=randomUUID();await query("INSERT INTO meetings(id,org_id,unit_id,owner_id,title,platform,join_url,scheduled_at,template_id,consent,status) VALUES($1,$2,$3,$4,'Synthetic stop test','Teams','https://teams.microsoft.com/l/meetup-join/test',now()+interval '1 hour',$5,true,'SETUP_REQUIRED')",[id,org,unit,user,template]);const row=(await query('SELECT * FROM meetings WHERE id=$1',[id])).rows[0];await tx(async db=>{await queueCapture(db,row);await db.query("UPDATE jobs SET run_at='2100-01-01' WHERE meeting_id=$1",[id]);});return row;}
  async function stop(row){await tx(async db=>{await db.query('SELECT id FROM meetings WHERE id=$1 FOR UPDATE',[row.id]);await queueCaptureStop(db,row);await db.query("UPDATE jobs SET run_at='2100-01-01' WHERE meeting_id=$1",[row.id]);});}
  const pending=await fixture();await stop(pending);globalThis.fetch=async()=>{throw new Error('Cancelled dispatch must never call provider');};await runCaptureJob({type:'CAPTURE_CREATE'},pending,process.env.DATA_DIR);assert.equal((await query('SELECT status FROM meetings WHERE id=$1',[pending.id])).rows[0].status,'CANCELLED');
  const scheduled=await fixture(),scheduledBot=randomUUID();globalThis.fetch=async()=>Response.json({id:scheduledBot});await runCaptureJob({type:'CAPTURE_CREATE'},scheduled,process.env.DATA_DIR);await stop(scheduled);const methods=[];globalThis.fetch=async(url,options)=>{methods.push(options.method);assert.ok(String(url).endsWith(`/bot/${scheduledBot}/`));return options.method==='GET'?Response.json({join_at:new Date(Date.now()+3600000).toISOString()}):new Response(null,{status:204});};await runCaptureJob({type:'CAPTURE_STOP'},scheduled,process.env.DATA_DIR);await runCaptureJob({type:'CAPTURE_STOP'},scheduled,process.env.DATA_DIR);assert.deepEqual(methods,['GET','DELETE']);assert.equal((await query('SELECT status FROM meetings WHERE id=$1',[scheduled.id])).rows[0].status,'CANCELLED');
  const live=await fixture(),liveBot=randomUUID();globalThis.fetch=async()=>Response.json({id:liveBot});await runCaptureJob({type:'CAPTURE_CREATE'},live,process.env.DATA_DIR);await stop(live);let left=false;globalThis.fetch=async(url,options)=>{if(options.method==='GET')return Response.json({join_at:null});assert.ok(String(url).endsWith(`/bot/${liveBot}/leave_call/`));assert.equal(options.method,'POST');left=true;return new Response(null,{status:204});};await runCaptureJob({type:'CAPTURE_STOP'},live,process.env.DATA_DIR);assert.equal(left,true);assert.equal((await query('SELECT status FROM meetings WHERE id=$1',[live.id])).rows[0].status,'STOPPING_CAPTURE');
  const rejected=await fixture();globalThis.fetch=async()=>new Response(null,{status:401});await assert.rejects(runCaptureJob({type:'CAPTURE_CREATE'},rejected,process.env.DATA_DIR),/HTTP 401/);assert.equal((await query('SELECT state FROM capture_sessions WHERE meeting_id=$1',[rejected.id])).rows[0].state,'REJECTED');await stop(rejected);assert.equal((await query('SELECT status FROM meetings WHERE id=$1',[rejected.id])).rows[0].status,'CANCELLED');
  const uncertain=await fixture();let uncertainCalls=0;globalThis.fetch=async()=>{uncertainCalls++;throw new Error('network interrupted');};await assert.rejects(runCaptureJob({type:'CAPTURE_CREATE'},uncertain,process.env.DATA_DIR),/uncertain/);await assert.rejects(runCaptureJob({type:'CAPTURE_CREATE'},uncertain,process.env.DATA_DIR),/Recover the bot ID/);assert.equal(uncertainCalls,1);assert.equal((await query('SELECT state FROM capture_sessions WHERE meeting_id=$1',[uncertain.id])).rows[0].state,'UNKNOWN');
  // Configuration changes invalidate readiness, but cannot interrupt active sessions.
  assert.equal((await request('/admin/capture/Teams','PUT',{...config,secret:'replacement-synthetic-key'},a)).status,409);
  await query("UPDATE capture_sessions SET state='ENDED' WHERE org_id=$1",[org]);
  assert.equal((await request('/admin/capture/Teams','PUT',{...config,secret:'replacement-synthetic-key'},a)).status,200);
  const reset=(await request('/admin/capture/Teams','GET',null,a)).data;assert.equal(reset.checked_at,null);assert.equal(reset.webhook_checked_at,null);
  assert.equal((await request('/admin/capture/Teams','PUT',{...config,transcriptionProvider:'elevenlabs',secret:'recall-transcript-key'},a)).status,200);
  assert.equal((await request('/admin/capture/Teams','GET',null,a)).data.config.transcriptionProvider,'recall');
 }finally{
  globalThis.fetch=originalFetch;if(savedPath){const {unlink}=await import('node:fs/promises');await unlink(savedPath).catch(()=>{});}
  for(const table of ['capture_webhooks','capture_sessions','capture_connections','audit','integrations'])await query(`DELETE FROM ${table} WHERE org_id=ANY($1::uuid[])`,[[org,other]]);
  await query('DELETE FROM sessions WHERE user_id IN (SELECT id FROM users WHERE org_id=ANY($1::uuid[]))',[[org,other]]);
  for(const table of ['jobs','usage','minutes','transcripts'])await query(`DELETE FROM ${table} WHERE meeting_id IN (SELECT id FROM meetings WHERE org_id=ANY($1::uuid[]))`,[[org,other]]);
  for(const table of ['meetings','templates','users','units','organizations'])await query(`DELETE FROM ${table} WHERE ${table==='organizations'?'id':'org_id'}=ANY($1::uuid[])`,[[org,other]]);await pool.end();
 }
});
