import { Document, Packer, Paragraph, TextRun, HeadingLevel, Footer, PageNumber } from 'docx';
import PDFDocument from 'pdfkit';
import { existsSync } from 'node:fs';
export function documentLines(meeting,minutes,segments){
 const lines=[{kind:'title',text:meeting.title},{kind:'status',text:minutes.status==='APPROVED'?`APPROVED · Version ${minutes.version}`:'DRAFT — NOT APPROVED'},
 {text:`Meeting: ${new Date(meeting.scheduled_at).toLocaleString('en-GB',{timeZone:meeting.timezone})} (${meeting.timezone})`},
 {text:`Platform: ${meeting.platform} | Template: ${minutes.template_snapshot?.name||'Project progress'} v${minutes.template_snapshot?.version||1}`},
 {text:`Attendees: ${(minutes.content.attendees||[]).join(', ')||'Not stated'}`},
 {text:minutes.approved_at?`Approved: ${new Date(minutes.approved_at).toISOString()}`:'Approval pending'},
 {kind:'heading',text:'Summary'},{text:minutes.content.summary}];
 for(const type of ['discussion','decision','action','question']){lines.push({kind:'heading',text:{discussion:'Discussion',decision:'Decisions',action:'Action register',question:'Open questions'}[type]});const items=minutes.content.items.filter(i=>i.type===type);if(!items.length)lines.push({text:'Not stated'});for(const item of items){lines.push({text:item.text});if(type==='action')lines.push({text:`Owner: ${item.owner||'Not stated'} | Due: ${item.dueDate||'Not stated'}`});const s=segments.find(s=>s.id===item.evidence);if(s)lines.push({kind:'evidence',text:`Evidence ${Math.floor(s.start/60)}:${String(Math.floor(s.start%60)).padStart(2,'0')} · ${s.speaker}: ${item.quote||s.text}`});}}
 lines.push({kind:'heading',text:'Next meeting'},{text:minutes.content.nextMeeting||'Not stated'});if(meeting.sample)lines.push({kind:'status',text:'SAMPLE DATA — NOT A REAL MEETING RECORD'});return lines;
}
export async function exportDocx(lines){const document=new Document({styles:{default:{document:{run:{font:'Calibri',size:22},paragraph:{spacing:{after:140}}}}},sections:[{properties:{page:{margin:{top:1000,bottom:1000,left:1100,right:1100}}},footers:{default:new Footer({children:[new Paragraph({children:[new TextRun('AI Minutes | Page '),new TextRun({children:[PageNumber.CURRENT]})]})]})},children:lines.map(line=>new Paragraph({heading:line.kind==='title'?HeadingLevel.TITLE:line.kind==='heading'?HeadingLevel.HEADING_1:undefined,children:[new TextRun({text:line.text||'',bold:line.kind==='status',color:line.kind==='status'?'92400E':line.kind==='evidence'?'586779':'111827',size:line.kind==='evidence'?18:undefined})]}))}]});return Packer.toBuffer(document);}
export async function exportPdf(lines){return new Promise((resolve,reject)=>{const doc=new PDFDocument({size:'A4',margin:52,info:{Title:lines[0].text,Author:'AI Minutes'}});const chunks=[];doc.on('data',c=>chunks.push(c));doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject);const font='/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc';if(existsSync(font))doc.font(font,'NotoSansCJKtc-Regular');for(const line of lines){doc.fontSize(line.kind==='title'?23:line.kind==='heading'?15:line.kind==='evidence'?9:10).fillColor(line.kind==='status'?'#92400e':'#182335').text(line.text||' ',{lineGap:4});doc.moveDown(line.kind==='heading'?0.4:0.7);}doc.end();});}
